name: siqad # you probably want to 'snapcraft register <name>'
base: core18 # the base snap is the execution environment for this snap
version: '0.2.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: SiQAD GUI for designing atomic silicon quantum dot assemblies. # 79 char long summary
description: |
  SiQAD (Silicon Quantum Atomic Designer) is a next-generation CAD tool
  that enables the design and simulation of silicon dangling bond (Si-DB)
  circuits through an intuitive graphical user interface (GUI) and a
  modular simulation back-end. Please read our publication on IEEE TNANO
  (doi 10.1109/TNANO.2020.2966162).

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  siqad:
    extensions:
      - kde-neon  # provides necessary Qt5 dependencies and sets up the desktop environment
    command: bin/siqad
    plugs: [unity7, x11, home]

parts:
  # SiQAD build dependencies
  siqad-deps:
    plugin: nil
    build-packages: [make,gcc,g++,qtchooser,qt5-default,libqt5svg5-dev,qttools5-dev,qttools5-dev-tools,libqt5charts5,libqt5charts5-dev,libboost-dev,libboost-filesystem-dev,libboost-system-dev,libboost-thread-dev,libboost-random-dev,swig]

  # SiQADConnector dependencies
  siqadconn-deps:
    plugin: python
    python-packages:
      - scikit-build
    build-packages: [python3-pip,python3-tk,swig,libboost-dev,cmake]

  # AFM-Sim dependencies
  plugin-deps:
    plugin: python
    python-packages:
      - PySide2
    stage-packages:
      - python3-pip
      - python3-matplotlib
      - python3-numpy
      - python3-scipy

  # NOTE: python3-dolfin cannot be packaged, see:
  # https://forum.snapcraft.io/t/error-when-including-python3-dolfin-as-a-stage-package/17752
  #poissolver-deps:
  #  plugin: nil
  #  stage-packages:
  #    - gmsh
  #    - python3-dolfin
  #    - python3-networkx
  #    - python3-shapely

  # Full SiQAD CMake
  siqad:
    source: https://github.com/siqad/siqad.git
    source-type: git
    source-branch: dev
    #source: siqadsrc.zip
    #source-type: zip
    plugin: cmake
    configflags: [-DCMAKE_BUILD_TYPE=Release, -DCMAKE_INSTALL_PREFIX=/bin, -DSYMLINK_INSTALL_PREFIX=$SNAPCRAFT_PART_INSTALL/bin, -DSKIP_POISSOLVER=true]
    stage-packages:
      - libboost-random1.65.1
      - libboost-system1.65.1
      - libdouble-conversion1
      - libfreetype6
      - libgl1
      - libglvnd0
      - libglx0
      - libgraphite2-3
      - libharfbuzz0b
      - libicu60
      - libpng16-16
      - libqt5charts5
      - libqt5core5a
      - libqt5gui5
      - libqt5svg5
      - libqt5widgets5
      - libx11-6
      - libxau6
      - libxcb1
      - libxdmcp6
